version: '3.3'

services: 
    wordpress:
        image: wordpress
        restart: always
        ports:
        - 8080:80
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: dev-wesley
            WORDPRESS_DB_PASSWORD: mypass
            WORDPRESS_DB_NAME: wp-portfolio
        volumes:
            - ./src/wp-portfolio:/var/www/html/wp-content/themes/wp-portfolio

    db:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: wp-portfolio
            MYSQL_USER: dev-wesley
            MYSQL_PASSWORD: mypass
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes:
            - db:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8081:80
        environment:
            - PMA_ARBITRARY=1
        depends_on:
            - db
        networks:
            - back

networks: 
    back:
        
volumes: 
    db:
    wordpress:
