baseURL = 'https://wesley.github.io/'
languageCode = 'en-us'
title = 'Hugo Base Theme'
author = 'Wesley Bertipaglia'

[Author]
    name = 'Wesley Bertipaglia'

[Theme]
    favicon = '/static/icons/favicon.svg'